# yaml-language-server: $schema=https://raw.githubusercontent.com/rvben/rumdl/main/rumdl.schema.json
[global]
exclude = [".git", ".github"]
respect-gitignore = true

disable = ["MD033"]

[MD013]
line-length = 100
code-blocks = false
tables = false

[MD044]
names = ["rumdl", "Markdown", "GitHub"]
